<?php

define('FFM_LANG', '__FFM_LANG__');

$__FFM_LANG__ = array(
    'id' => 'en',
    'global' => array(
        'title' => 'Far from Moscow'
    ),
    'sys' => array(
        'u001' => 'User account not created.',
        'u002' => 'We have sent you an e-mail message with a confirmation link. Please check your mail now.',
        'u003' => 'The username or password you entered is incorrect.',
        'f001' => 'Required field cannot be left blank.',
        'f011' => 'Only these characters are allowed: letters, numbers, and some special characters.',
        'f012' => 'Enter a domain name after the \'@\'.',
        'f013' => 'Enter an email address with only one \'@\'.',
        'f014' => 'Don\'t forget to include the \'@\'.',
        'f015' => 'Enter a user name before the \'@\'.',
        'f016' => 'Your email address contains an invalid domain name.',
        'f017' => 'This email address is too long.',
        'f020' => 'Must have at least 6 characters.',
        'f021' => 'Must have at most 32 characters.',
        'f022' => 'Maximum allowed length is 100 characters.',
        'f023' => 'The password you selected is similar to your email. To protect the security of your account, please consider changing it.',
        'f024' => 'There\'s already an account associated with this email address.',
        'f025' => 'Maximum allowed length is 1000 characters.',
        'q001' => 'Your request was not sent',
        'q002' => 'Your request was sent successfully',
        'e001' => 'Permission denied',
        'e002' => 'System error. Please try again later',
        'e003' => 'Invalid upload',
        'e004' => 'Profile with such name already exists',
        'e005' => 'Please <span style="text-decoration: underline; cursor: pointer;" onclick="return popupLogin();">Log In</span>',
        'e006' => 'Profile with such name already added',
        'e007' => 'Email address does not exist',
    ),
    'menu' => array(
        'home' => 'Home',
        'artists' => 'Artists',
        'promoters' => 'Promo',
        'articles' => 'Articles',
        'video' => 'Video',
        'events' => 'Events',
        'label' => 'Label',
        'about' => 'About Us',
        'mobile' => 'Mobile version',
        'login' => 'Login',
        'logout' => 'Logout',
        'register' => 'Register',
        'podcast' => 'Our Podcast',
    ),
    'headers' => array(
        'artists' => 'Latest Artists',
        'articles' => 'Articles',
        'audio' => 'Audio',
        'video' => 'Video',
        'events' => 'Events',
        'label' => 'Label',
        'genres' => 'Genres',
        'top' => 'TOP-10',
        'promoters' => 'Promo',
        'about' => 'About “Far from Moscow”',
        'relatedArtists' => 'Related Artists',
        'promotersArtists' => 'Promoter\'s Artists',
        'releaseArtists' => 'Release Artists',
        'contactUs' => 'Contact Us',
        'submitVideo' => 'Submit your video',
        'new' => 'Registration for artists and<br> promoters is open!',
        'whatsnew' => 'What\'s new?',
        'recommends' => 'Recommends',
        'warning' => 'Please remember we like profiles to contain maximum information. As much audio, video, and images as possible! We would like FFM to be the best resource available – and the musicians deserve our respect, too.  We really don\'t like to see empty profiles – or anything out of date. Thanks for your understanding!',
        'artistPhotos' => array(
            'This Artist has no photos',
            'This Artist has $1 photo',
            'This Artist has $1 photos'
        ),
        'promoterPhotos' => array(
            'This Promoter has no photos',
            'This Promoter has $1 photo',
            'This Promoter has $1 photos'
        ),
    ),
    'filter' => array(
        'genres' => 'Filter by genres',
        'regions' => 'Regions',
        'genresAll' => 'All genres',
        'regionsAll' => 'All regions',
    ),
    'form' => array(
        'name' => 'Name',
        'email' => 'Email',
        'subject' => 'Subject',
        'link' => 'Link',
        'comment' => 'Comment',
        'submit' => 'Submit',
        'send' => 'Send Message',
    ),
    'auth' => array(
        'name' => 'Name',
        'email' => 'Your E-mail',
        'password' => 'Password',
        'remember' => 'Remember Me',
        'subscribe' => 'Subscribe me for all news',
        'forgot' => 'Forgot Your Password?',
        'facebook' => 'Login VIA Facebook',
        'login' => 'Log In',
        'register' => 'Register',
    ),
    'artist' => array(
        'titleNew' => 'New Artist',
        'tabArticles' => 'Articles',
        'tabEvents' => 'Events',
        'tabLabel' => 'Label',
        'tabReleases' => 'Releases',
        'tabAudio' => 'Audio',
        'tabPhotos' => 'Photos',
        'tabVideos' => 'Videos',
        'labelName' => 'In English',
        'labelNameRu' => 'In Russian',
        'name' => 'Name',
        'nameRu' => 'Name',
        'description' => 'Description',
        'links' => 'Links',
        'genres' => 'Genres',
        'geoText' => 'Location',
        'date' => 'Select Date',
        'eventName' => 'Title',
        'eventDescription' => 'Description',
        'eventAddress' => 'Address',
        'articlesEmpty' => 'Empty list',
        'releasesEmpty' => 'Empty list',
        'tracksEmpty' => 'Empty list',
        'audioEmpty' => 'Empty list',
        'photosEmpty' => 'Empty list',
        'eventEmpty' => 'Empty list',
        'eventDeleteConfirmation' => 'Do you really want to delete this event?',
        'photoDeleteConfirmation' => 'Do you really want to delete this photo?',
        'eventImageUploadNotification' => 'You may upload picture after saving.',
    ),
    'release' => array(
        'releaseEdit' => 'Edit Release',
        'name' => 'Name',
        'year' => 'Year',
        'label' => 'Label',
        'genres' => 'Genres',
        'releaseDeleteConfirmation' => 'Do you really want to delete this release?',
        'releaseImageUploadNotification' => 'You may upload an album cover after saving.',
        'downloadOnBandcamp' => 'Download on Bandcamp'
    ),
    'track' => array(
        'trackEdit' => 'Edit Track',
        'name' => 'Name',
        'year' => 'Year',
        'label' => 'Label',
        'genres' => 'Genres',
        'keywords' => 'Keywords',
        'description' => 'Description / Lyrics',
        'share' => 'Share for Downloading',
        'trackDeleteConfirmation' => 'Do you really want to delete this track?',
        'trackUploadNotification' => 'You may upload mp3 file after saving.',
    ),
    'promoter' => array(
        'titleNew' => 'New Promoter',
        'tabArticles' => 'Articles',
        'tabEvents' => 'Events',
        'tabLabel' => 'Label',
        'tabVideos' => 'Videos',
        'tabPhotos' => 'Photos',
        'labelName' => 'In English',
        'labelNameRu' => 'In Russian',
        'name' => 'Name',
        'nameRu' => 'Name',
        'description' => 'Description',
        'links' => 'Links',
        'extra' => 'Current events, up-to-date information, etc.',
        'genres' => 'Genres',
        'geoText' => 'Location',
        'artistDeleteConfirmation' => 'Do you really want to delete this artist?',
    ),
    'link' => array(
        'share' => 'Share this page via',
        'shareTrack' => 'Share this track via',
        'getLink' => 'Get the link',
        'embedCode' => 'Embed code',
        'facebook' => 'Facebook',
        'vkontakte' => 'VK',
        'twitter' => 'Twitter',
        'addRelease' => 'Add Album',
        'addEvent' => 'Add Event',
        'addArtist' => 'New Artist Profile',
        'addPromoter' => 'New Promoter Profile',
        'addTrack' => 'Add Track',
        'addPhoto' => 'Add Photos',
        'upload' => 'Upload',
        'edit' => 'Edit',
        'editMini' => 'Edit',
        'save' => 'Save',
        'saveMini' => 'Save',
        'cancel' => 'Cancel',
        'delete' => 'Delete',
        'searchField' => 'search',
        'allVideos' => 'All Video',
        'addPromotersArtist' => 'Search',
    ),
    'user' => array(
        'forgotTitle' => 'Forgot your password?',
        'forgotText' => 'To reset your password, type your email address.',
        'forgotEmail' => 'Email address',
        'forgotSubmit' => 'Submit',
        'forgotSent' => 'Recovery Email Sent',
        'forgotInstructions' => 'To reset your password, follow the instructions sent to your email address.',
        'forgotChange' => 'To change the password for your account, click the link below:',
        'forgotCopyLink' => 'If clicking the link above doesn\'t work, please copy and paste the URL in a new browser window instead.',
        'forgotMessage' => 'If you\'ve received this mail in error, it\'s likely that another user entered your email address by mistake while trying to reset a password. If you didn\'t initiate the request, you don\'t need to take any further action and can safely disregard this email.',
        'forgotSubject' => 'Your Password',
        'forgotPasswordTitle' => 'Enter a new password',
        'forgotPassword' => 'password',
        'forgotPasswordChanged' => 'The password is changed',
        'myPages' => 'My Pages',
        'findLabel' => 'Find artist profile',
        'findText' => 'artist name',
        'request' => 'Request',
        'text' => 'Request for',
        'labelEmail' => 'Email',
        'labelText' => 'Introduce yourself',
        'buttonSend' => 'Send',
    ),
    'comment' => array(
        'wall' => 'Wall',
        'title' => 'Comments',
        'text' => 'Comment',
        'login' => 'Only registered users may leave comments.',
    ),
    'label' => array(
        'labelArtists' => 'Label artists',
        'variousArtists' => 'Various artists',
        'showAllArtists' => 'Show all artists',
        'hideArtists' => 'Hide'
    )
);
